### PR TITLE
feat: add a nginx icon

### PR DESCRIPTION
**Pull request by r3nya**
Issue #33
@oivva btw, I noticed that [nginx.tmLanguage](https://github.com/brandonwamboldt/sublime-nginx/blob/master/Syntaxes/nginx.tmLanguage) has this params:
```xml
<key>name</key>
<string>nginx</string>
…
<key>scopeName</key>
<string>source.nginx</string>
```
And because of this I set this rules:
```json
"file_type_nginx": {
    "color": "green",
    "syntaxes": [
      {
        "name": "nginx",
        "scope": "source.nginx"
      }
    ]
  },
```

Is it ok? :)

### CODE REVIEW

**Comment by oivva** [comment]
Everything is ok with rules. But you have to resize svg icon with respecting its aspect ratio.

See .

**Comment by r3nya** [comment]
@oivva Hm … Yeah. One moment I will look.

**Comment by r3nya** [comment]
@oivva can I do icon size as 16x14?

**Comment by oivva** [comment]
Also for better look I recommend to leave 1-2px margins.



White - viewport
Black - icon sizes

**Comment by oivva** [comment]
In your case the best size is:

16x16 - viewport
14x12 - icon

**Comment by r3nya** [comment]
@oivva please review my changes. :)

**Comment by oivva** [comment]
Nope :smile: Change it to this:

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
  <defs>
    <style>
      .i-color {
        fill: #000;
        fill-rule: evenodd;
      }
    </style>
  </defs>
  <path id="file_type_nginx.svg" class="i-color" d="M11.661,14H4.47L0.98,8.081,4.454,2h7.494l1.987,4.5H11.342L10.326,4.505H5.987L4.977,6.273,3.954,8.066l2.018,3.443h4.081l0.774-1.524H7.644A1.273,1.273,0,0,1,6.337,8.747,1.385,1.385,0,0,1,7.644,7.48H15Z" transform="translate(0 -1)"/>
</svg>
```

**Comment by r3nya** [comment]
LOL, ok. :)

**Comment by r3nya** [comment]
I did it. Please merge :)

**Comment by oivva** [comment]
I'll describe later in the contributing, how to adapt the icon for better quality in:

* Sketch
* Adobe Photoshop
* Adobe Illustrator
* Inkscape

**Pull request merged**
