### PR TITLE
Added icon for Yarn

### PR DESCRIPTION
**Pull request by r3nya**
Hello!

I like your job and I want to help you.
I added icon for `yarn.lock` file, please review my changes. Maybe I did something wrong. :)

PS: It's request #9

### CODE REVIEW

**Comment by r3nya** [comment]
Hi @oivva. Gotcha, I will fix it soon. Thanks. :)

**Comment by oivva** [comment]
Also I'm sorry I was inattentive, I've added this icon recently but I didn't have time to push the changes. So I'll close this PR, but the notes are relevant for #26, #27.

**Comment by r3nya** [comment]
@oivva ok mate. I'm reading CONTRIBUTING.md right now, and I will send correct PRs. :)

**Comment by oivva** [comment]
@r3nya Thanks :wink:

**Pull request closed without merging**
